<a href="https://colab.research.google.com/github/alvas-education-foundation/Dhanya-Shetty_026/blob/master/Pythonic_code_Day_3_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd # Import Panda Library
# Program to Create series with scalar values
Data =[1, 3, 4, 5, 6, 2, 9] # Numeric data
# Creating series with default index values
s = pd.Series(Data)
print(s)
# predefined index values
Index =['a', 'b', 'c', 'd', 'e', 'f', 'g']
# Create series with Data, and Index
a = pd.Series(Data, index = Index)
a

0    1
1    3
2    4
3    5
4    6
5    2
6    9
dtype: int64


a    1
b    3
c    4
d    5
e    6
f    2
g    9
dtype: int64

In [2]:
#Converting Pandas Series to Python list

import pandas as pd
ds = pd.Series([2, 4, 6, 8, 10])
print("Pandas Series")
print(ds)
print("Convert Pandas Series to Python list")
ds.tolist()

Pandas Series
0     2
1     4
2     6
3     8
4    10
dtype: int64
Convert Pandas Series to Python list


[2, 4, 6, 8, 10]

In [5]:
#program to Create Dictionary into Series

dictionary ={'a':1, 'b':2, 'c':3, 'd':4, 'e':5, 'f':6}
# Creating series of Dictionary type
sd = pd.Series(dictionary)
sd

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

In [6]:
#Program to Create ndarray series

Data =[[2, 3, 4], [5, 6, 7]] # Defining 2darray
print(Data)
# Creating series of 2darray
snd = pd.Series(Data)
snd

[[2, 3, 4], [5, 6, 7]]


0    [2, 3, 4]
1    [5, 6, 7]
dtype: object

In [7]:
#Program to Create DataFrame
import pandas as pd
# Import Library
a = pd.DataFrame(Data)
a

0  1  2
0  2  3  4
1  5  6  7

In [8]:
#converting multiple dictionaries into pandas data frame

dict1 ={'a':35.2,'b':47,'c':77,'d':49} # Define Dictionary 1
dict2 ={'a':53,'b':69,'c':79,'d':81,'e':91} # Define Dictionary 2
dict3 ={'a':56,'b':98,'c':77,'d':81,'e':90} # Define Dictionary 3
Data = {'Maths':dict1, 'Physics':dict2,'Chemistry': dict3} # Define Data with dict1
df = pd.DataFrame(Data)
df

Maths  Physics  Chemistry
a   35.2       53         56
b   47.0       69         98
c   77.0       79         77
d   49.0       81         81
e    NaN       91         90

In [11]:
import pandas as pd
df = pd.DataFrame({'X':[78,85,96,80,86], 'Y':[84,94,89,83,86],'Z':[86,97,96, 72,83]});
print(df)


    X   Y   Z
0  78  84  86
1  85  94  97
2  96  89  96
3  80  83  72
4  86  86  83


In [12]:
#Write a program to create the mean and standard deviation, maximum and minimum of the data of a given Series using pandas
import pandas as pd
s = pd.Series(data = [1,2,3,4,5,6,7,8,9,5,3])
print("Original Data Series:") 
print(s)
print("Mean of the said Data Series:") 
print(s.mean())
 

print("Standard deviation of the said Data Series:") 
print(s.std())
print("Max")
print(s.max())
print("Min")
print(s.min())

Original Data Series:
0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9     5
10    3
dtype: int64
Mean of the said Data Series:
4.818181818181818
Standard deviation of the said Data Series:
2.522624895547565
Max
9
Min
1


In [13]:
#Write a Pandas program to create a subset of a given series based on value and condition 2 python
import pandas as pd
s = pd.Series([0, 1,2,3,4,5,6,7,8,9,10])
print("Original Data Series:") 
print(s)
n = 6
new_s = s[s > n]
print("The values greater than 6") 
print(new_s)
new_s1=s[s%2!=0] 
print("The odd values ") 
print(new_s1)

Original Data Series:
0      0
1      1
2      2
3      3
4      4
5      5
6      6
7      7
8      8
9      9
10    10
dtype: int64
The values greater than 6
7      7
8      8
9      9
10    10
dtype: int64
The odd values 
1    1
3    3
5    5
7    7
9    9
dtype: int64


In [14]:
#program to sort a given Series.
import pandas as pd
s = pd.Series(['200','100', 'python', '300.12', '400'])
print("Original Data Series:") 
print(s)
new_s = pd.Series(s).sort_values() 
print("sorted series are") 
print(new_s)

Original Data Series:
0       200
1       100
2    python
3    300.12
4       400
dtype: object
sorted series are
1       100
0       200
3    300.12
4       400
2    python
dtype: object


In [15]:
#Write a Pandas program to change the data type of the given meric ['100', '200', 'python', '300.12', '400a']
import pandas as pd
s1 = pd.Series(['100', '200', 'python', '300.12', '400a'])
print("Original Data Series:") 
print(s1)
print("Change the said data type to numeric:") 
s2 = pd.to_numeric(s1, errors='coerce') 
print(s2)

Original Data Series:
0       100
1       200
2    python
3    300.12
4      400a
dtype: object
Change the said data type to numeric:
0    100.00
1    200.00
2       NaN
3    300.12
4       NaN
dtype: float64


In [16]:
#Numpyt example program
import numpy as np
 
np.random.seed(0)	# seed for reproducibility

x1 = np.random.randint(100, size=6)	# One-dimensional array
x2 = np.random.randint(100, size=(3, 4))	# Two-dimensional array
x3 = np.random.randint(100, size=(3, 4, 5))	# Three-dimensional array print(x1)
print(x2) 
print(x3)

[[83 21 36 87]
 [70 88 88 12]
 [58 65 39 87]]
[[[46 88 81 37 25]
  [77 72  9 20 80]
  [69 79 47 64 82]
  [99 88 49 29 19]]

 [[19 14 39 32 65]
  [ 9 57 32 31 74]
  [23 35 75 55 28]
  [34  0  0 36 53]]

 [[ 5 38 17 79  4]
  [42 58 31  1 65]
  [41 57 35 11 46]
  [82 91  0 14 99]]]


In [17]:
#Write a Pandas program to convert a NumPy array to a Pandas series.Sample NumPy array: d1 = [10, 20, 30, 40, 50]
import numpy as np 
import pandas as pd
np_array = np.array([1, 2, 3, 4, 5]) 
print("NumPy array:") 
print(np_array)
new_series = pd.Series(np_array) 
print("Converted Pandas series:") 
print(new_series)

NumPy array:
[1 2 3 4 5]
Converted Pandas series:
0    1
1    2
2    3
3    4
4    5
dtype: int64
